### ISSUE TITLE
Why does commit check use a lock?

### ISSUE THREAD

**Issue by AceHack** [jbakic/Shielded#15] opened 2019-02-11 01:53 UTC
Is it possible to be completely lock-free at least for some subset of operations?

**Comment by jbakic** [comment] 2019-02-15 13:23
Hello! The answer is to the title question is: because it's simpler that way :) There is a branch here, LockFree, which avoids using the global check lock, take a look at it. However, that version is more complex, and it's unfortunately not correct. It has a nasty race bug which only happens rarely, and I have not yet managed to determine the root cause. And, on top of that, it still does not fully satisfy the lock-free definition - threads should be able to help each other, i.e. perform the transaction check and the writing for another thread if that other thread is blocking us, which would add even more complexity - and it is also slower.

Since the global check lock is held for a short time, only during the check and not during the writing, I concluded that the complexity is not worth it. So, I'd like to close this issue. Keeping it open for now, let me know what you think.

**Closed** 2019-02-24 17:15 UTC
